---
title: "The Game Contest"
subtitle: "Due: December 15, 2023"
format:
  html:
    theme:
      light: 
        - cosmo
        - psets.scss
      dark: darkly
    fontsize: 1.2em
    highlight-style: atom-one
    toc: true
    toc-depth: 2
    html-math-method: katex
    embed-resources: true
    title-block-banner: GameContestCover.png
    title-block-banner-color: black
    smooth-scroll: true
---

Throughout the course of the semester, you have learned many new techniques, tools, and libraries you can utilize in your approach to writing a particular piece of code. For the last contest of the semester, I wanted to open things up in a fun, entertaining way. So for the last contest of the semester, your challenge is to write a simple game. You can use **any** of the tools or libraries we have learned about over the semester. Your game can have graphical elements using PGL, or it could be entirely text-based, such as the Adventure Game. I am completely fine, in fact, if you want to build off of an already existing project by greatly extending something like the Breakout Project or the Adventure Project. There are no bonus points for complexity here though, so a simple game entirely of your own devising would be on an equal playing field with something as complex as the Adventure Project.

Each of you is eligible to submit one entry for the contest, where an entry consists of a program that implements a particular game of your choosing. To get started, you can grab the starting template by following the below link.

```{=html}
<a href='https://classroom.github.com/a/kOqfo__o' target="_blank" class="btn btn-info" style='margin:auto; display: block; width:50%;'>Give me the materials!</a>
```
<br>

# Selection Criteria
Assuming 10 or more total submissions, a prize will be awarded in each of two categories:

- _Polished Gem_ -- This prize is awarded to the program with exhibits the greatest amount of polish. The game may be simple, but the controls are tight, the interface (if any) is well designed and constructed, and the bugs and few and far between.
- _Fun Factor_ -- This prize will be based on the game that pulls me in and entertains me the most. Maybe it is not the prettiest, or it has some bugs. But if it is a joy to play, then this award might be yours!

If fewer than 10 entries are received, then only a single joint prize will be awarded. In both categories, programming style will be part of the evaluation. You do not need to specify a category; all entries will be eligible for either prize.

# Prizes
The grand prize in each of the categories will be that I will replace whatever individual score most negatively affects your grade--which may be a problem set, project, or exam--with a 100% in the computation of the final grade. Those who submit serious entries will also get complementary prize in form of grades between 80-95% which can be used to replace score that most negatively affects your grade - a problem set, project, or exam.

# Official Rules

#. Only students registered in CS 151 are eligible to submit entries in the contest.
#. Only one entry per person will be accepted.
#. All entries must be submitted by 11:59pm on Sunday, December 10th.
#. If your program requires libraries beyond those we have used this semester, you must clearly indicate what is needed. And understand that, unless you have tested it on other systems, not all libraries work identically on different systems.
#. Contest entries should be sensitive to Willamette's individual and cultural diversity. Programs that have the effects of perpetuating negative stereotypes will not be considered for prizes.
