---
title: "Presonal Project"
subtitle: "Due: April 15, 2024"
format:
  html:
    theme:
      light: 
        - cosmo
        - psets.scss
      dark: darkly
    fontsize: 1.2em
    highlight-style: atom-one
    toc: true
    toc-depth: 2
    html-math-method: katex
    embed-resources: true
    title-block-banner: linear-gradient(120deg, rgba(156, 79, 150, 1) 0%, rgba(255, 99, 85, 1) 20%, rgba(251,169,73,1) 40%, rgba(250, 228, 66, 1) 60%, rgba(139,212,72,1) 80%, rgba(42, 168, 242, 1) 100%)
    title-block-banner-color: white
    smooth-scroll: true
---


As exciting as there were, the graphics projects you have completed including Breakout game only scratches the surface of what you can do with the Portable Graphics Library. To give you a chance to explore the capabilities of the library in greater depth, I am introducing __Personal Project__ which is different from the *defined ones*.

Each of you MUST submit one entry for the personal project, where an entry consists of a program that uses the Portable Graphics Library. You are free to use any of the capabilities in that library, including those described in the online documentation. To get started, you can grab a starting repository by clicking on the button below. Make sure you fill out the top metadata on the main program file please!

```{=html}
<a href='https://classroom.github.com/a/kUI1AbrM' target="_blank" class="btn btn-info" style='margin:auto; display: block; width:50%;'>Grab the starting repository</a>
```
<br>

# Expectations and Rubrics
The project grade will will be awarded in each of two categories:

- **Quality** - Points here will be based on workability of your program, *appropraite comments* for functions and important sections in your program, and no errors reported in the terminal. 

- **Aesthetic merit** – Points here will be based on the aesthetic value of the submission.

- **Algorithmic sophistication** – The submission will receive points be based on the difficulty of the underlying programming and the sophistication of the displayed images, annimations, or interactions.

In all categories, programming style will be part of the evaluation. Please note that you do not need to specify a category; all entries will be eligible and evaluated accordingly.

# Official Rules:

1. Make sure you fill out the top metadata on the main program file named __Project_Entry.py__ and briefly introduce your project so that readers can understand what the program entails and can at least engage with it!

2. All entries must be submitted by 10:00pm on Monday, April 15.

3. Only one entry per person will be accepted.

4. You are required to do all your graphical operations using the classes from the Portable
Graphics Library. In particular, you may not dig into the source code for pgl.py and
use other features of the TKinter library on which PGL is based.

5. Your entry may not set a window size larger than 1024x768 pixels.

