# File: english.py

"""
This module defines a constant array called ENGLISH_WORDS that contains
an alphabetized list of English words and a function isEnglishWord(s)
that tests whether the string s is a legal English word.  All words are
stored in lower case.
"""

def isEnglishWord(s):
    """
    Returns True if s is a valid English word.
    """
    s = s.lower()
    lh = 0
    rh = len(ENGLISH_WORDS) - 1
    while lh <= rh:
        mid = (lh + rh) // 2
        if s == ENGLISH_WORDS[mid]:
            return True
        if s < ENGLISH_WORDS[mid]:
            rh = mid - 1
        else:
            lh = mid + 1
    return False

is_english_word = isEnglishWord

# Constants

ENGLISH_WORDS = ["abandon", "ability", "able", "abortion", "about", "above", "abroad", 
        "absence", "absolute", "absolutely", "absorb", "abuse", "academic", 
        "accept", "access", "accident", "accompany", "accomplish", "according", 
        "account", "accurate", "accuse", "achieve", "achievement", "acid", "acknowledge", 
        "acquire", "across", "act", "action", "active", "activist", "activity", "actor",
        "actress", "actual", "actually", "ad", "adapt", "add", "addition", "additional", 
        "address", "adequate", "adjust", "adjustment", "administration", "administrator", 
        "admire", "admission", "admit", "adolescent", "adopt", "adult", "advance", 
        "advanced", "advantage", "adventure", "advertising", "advice", "advise", "adviser",
        "advocate", "affair", "affect", "afford", "afraid", "african", "african-american", 
        "after", "afternoon", "again", "against", "age", "agency", "agenda", "agent", 
        "aggressive", "ago", "agree", "agreement", "agricultural", "ah", "ahead", "aid", 
        "aide", "aids", "aim", "air", "aircraft", "airline", "airport", "album", "alcohol", 
        "alive", "all", "alliance", "allow", "ally", "almost", "alone", "along", "already", 
        "also", "alter", "alternative", "although", "always", "am", "amazing", "american", 
        "among", "amount", "analysis", "analyst", "analyze", "ancient", "and", "anger", 
        "angle", "angry", "animal", "anniversary", "announce", "annual", "another", "answer", 
        "anticipate", "anxiety", "any", "anybody", "anymore", "anyone", "anything", "anyway", 
        "anywhere", "apart", "apartment", "apparent", "apparently", "appeal", "appear", 
        "appearance", "apple", "application", "apply", "appoint", "appointment", "appreciate", 
        "approach", "appropriate", "approval", "approve", "approximately", "arab", "architect", 
        "area", "argue", "argument", "arise", "arm", "armed", "army", "around", "arrange", 
        "arrangement", "arrest", "arrival", "arrive", "art", "article", "artist", "artistic", 
        "as", "asian", "aside", "ask", "asleep", "aspect", "assault", "assert", "assess", 
        "assessment", "asset", "assign", "assignment", "assist", "assistance", "assistant", 
        "associate", "association", "assume", "assumption", "assure", "at", "athlete", 
        "athletic", "atmosphere", "attach", "attack", "attempt", "attend", "attention", 
        "attitude", "attorney", "attract", "attractive", "attribute", "audience", "author", 
        "authority", "auto", "available", "average", "avoid", "award", "aware", "awareness", 
        "away", "awful", "baby", "back", "background", "bad", "badly", "bag", "bake", "balance", 
        "ball", "ban", "band", "bank", "bar", "barely", "barrel", "barrier", "base", "baseball", 
        "basic", "basically", "basis", "basket", "basketball", "bathroom", "battery", "battle", 
        "be", "beach", "bean", "bear", "beat", "beautiful", "beauty", "because", "become", 
        "bed", "bedroom", "beer", "before", "begin", "beginning", "behavior", "behind", "being", 
        "belief", "believe", "bell", "belong", "below", "belt", "bench", "bend", "beneath", 
        "benefit", "beside", "besides", "best", "bet", "better", "between", "beyond", "bible", 
        "big", "bike", "bill", "billion", "bind", "biological", "bird", "birth", "birthday", 
        "bit", "bite", "black", "blade", "blame", "blanket", "blind", "block", "blood", "blow", 
        "blue", "board", "boat", "body", "bomb", "bombing", "bond", "bone", "book", "boom", 
        "boot", "border", "born", "borrow", "boss", "both", "bother", "bottle", "bottom", "boundary", 
        "bowl", "box", "boy", "boyfriend", "brain", "branch", "brand", "bread", "break", "breakfast", 
        "breast", "breath", "breathe", "brick", "bridge", "brief", "briefly", "bright", "brilliant", "bring", 
        "british", "broad", "broken", "brother", "brown", "brush", "buck", "budget", "build", "building", 
        "bullet", "bunch", "burden", "burn", "bury", "bus", "business", "busy", "but", "butter", "button", 
        "buy", "buyer", "by", "cabin", "cabinet", "cable", "cake", "calculate", "call", "camera", "camp", 
        "campaign", "campus", "can", "canadian", "cancer", "candidate", "cap", "capability", "capable", 
        "capacity", "capital", "captain", "capture", "car", "carbon", "card", "care", "career", "careful", 
        "carefully", "carrier", "carry", "case", "cash", "cast", "cat", "catch", "category", "catholic", 
        "cause", "ceiling", "celebrate", "celebration", "celebrity", "cell", "center", "central", "century", 
        "ceo", "ceremony", "certain", "certainly", "chain", "chair", "chairman", "challenge", "chamber", 
        "champion", "championship", "chance", "change", "changing", "channel", "chapter", "character", 
        "characteristic", "characterize", "charge", "charity", "chart", "chase", "cheap", "check", "cheek", 
        "cheese", "chef", "chemical", "chest", "chicken", "chief", "child", "childhood", "chinese", "chip", 
        "chocolate", "choice", "cholesterol", "choose", "christian", "christmas", "church", "cigarette", 
        "circle", "circumstance", "cite", "citizen", "city", "civil", "civilian", "claim", "class", "classic", 
        "classroom", "clean", "clear", "clearly", "client", "climate", "climb", "clinic", "clinical", "clock", 
        "close", "closely", "closer", "clothes", "clothing", "cloud", "club", "clue", "cluster", "coach", "coal", 
        "coalition", "coast", "coat", "code", "coffee", "cognitive", "cold", "collapse", "colleague", 
        "collect", "collection", "collective", "college", "colonial", "color", "column", "combination", 
        "combine", "come", "comedy", "comfort", "comfortable", "command", "commander", "comment", "commercial", 
        "commission", "commit", "commitment", "committee", "common", "communicate", "communication", 
        "community", "company", "compare", "comparison", "compete", "competition", "competitive", 
        "competitor", "complain", "complaint", "complete", "completely", "complex", "complicated", 
        "component", "compose", "composition", "comprehensive", "computer", "concentrate", "concentration", 
        "concept", "concern", "concerned", "concert", "conclude", "conclusion", "concrete", "condition", 
        "conduct", "conference", "confidence", "confident", "confirm", "conflict", "confront", "confusion", 
        "congress", "congressional", "connect", "connection", "consciousness", "consensus", "consequence", 
        "conservative", "consider", "considerable", "consideration", "consist", "consistent", "constant", 
        "constantly", "constitute", "constitutional", "construct", "construction", "consultant", "consume", 
        "consumer", "consumption", "contact", "contain", "container", "contemporary", "content", "contest", 
        "context", "continue", "continued", "contract", "contrast", "contribute", "contribution", "control", 
        "controversial", "controversy", "convention", "conventional", "conversation", "convert", "conviction", 
        "convince", "cook", "cookie", "cooking", "cool", "cooperation", "cop", "cope", "copy", "core", 
        "corn", "corner", "corporate", "corporation", "correct", "correspondent", "cost", "cotton", "couch", 
        "could", "council", "counselor", "count", "counter", "country", "county", "couple", "courage", "course", 
        "court", "cousin", "cover", "coverage", "cow", "crack", "craft", "crash", "crazy", "cream", "create", 
        "creation", "creative", "creature", "credit", "crew", "crime", "criminal", "crisis", "criteria", 
        "critic", "critical", "criticism", "criticize", "crop", "cross", "crowd", "crucial", "cry", "cultural", 
        "culture", "cup", "curious", "current", "currently", "curriculum", "custom", "customer", "cut", 
        "cycle", "dad", "daily", "damage", "dance", "danger", "dangerous", "dare", "dark", "darkness", "data", 
        "date", "daughter", "day", "dead", "deal", "dealer", "dear", "death", "debate", "debt", "decade", "decide", 
        "decision", "deck", "declare", "decline", "decrease", "deep", "deeply", "deer", "defeat", "defend", 
        "defendant", "defense", "defensive", "deficit", "define", "definitely", "definition", "degree", "delay", 
        "deliver", "delivery", "demand", "democracy", "democrat", "democratic", "demonstrate", "demonstration", 
        "deny", "department", "depend", "dependent", "depending", "depict", "depression", "depth", "deputy", 
        "derive", "describe", "description", "desert", "deserve", "design", "designer", "desire", "desk", 
        "desperate", "despite", "destroy", "destruction", "detail", "detailed", "detect", "determine", 
        "develop", "developing", "development", "device", "devote", "dialogue", "die", "diet", "differ", 
        "difference", "different", "differently", "difficult", "difficulty", "dig", "digital", "dimension", 
        "dining", "dinner", "direct", "direction", "directly", "director", "dirt", "dirty", "disability", 
        "disagree", "disappear", "disaster", "discipline", "discourse", "discover", "discovery", "discrimination", 
        "discuss", "discussion", "disease", "dish", "dismiss", "disorder", "display", "dispute", "distance", 
        "distant", "distinct", "distinction", "distinguish", "distribute", "distribution", "district", "diverse", 
        "diversity", "divide", "division", "divorce", "dna", "do", "doctor", "document", "dog", "domestic", 
        "dominant", "dominate", "door", "double", "doubt", "down", "downtown", "dozen", "draft", "drag", 
        "drama", "dramatic", "dramatically", "draw", "drawing", "dream", "dress", "drink", "drive", "driver",
        "drop", "drug", "dry", "due", "during", "dust", "duty", "each", "eager", "ear", "early", "earn", 
        "earnings", "earth", "ease", "easily", "east", "eastern", "easy", "eat", "economic", "economics", 
        "economist", "economy", "edge", "edition", "editor", "educate", "education", "educational", "educator", 
        "effect", "effective", "effectively", "efficiency", "efficient", "effort", "egg", "eight", "either", 
        "elderly", "elect", "election", "electric", "electricity", "electronic", "element", "elementary", 
        "eliminate", "elite", "else", "elsewhere", "e-mail", "embrace", "emerge", "emergency", "emission", 
        "emotion", "emotional", "emphasis", "emphasize", "employ", "employee", "employer", "employment", 
        "empty", "enable", "encounter", "encourage", "end", "enemy", "energy", "enforcement", "engage", 
        "engine", "engineer", "engineering", "english", "enhance", "enjoy", "enormous", "enough", "ensure", 
        "enter", "enterprise", "entertainment", "entire", "entirely", "entrance", "entry", "environment", 
        "environmental", "episode", "equal", "equally", "equipment", "era", "error", "escape", "especially", 
        "essay", "essential", "essentially", "establish", "establishment", "estate", "estimate", "etc", 
        "ethics", "ethnic", "european", "evaluate", "evaluation", "even", "evening", "event", "eventually", 
        "ever", "every", "everybody", "everyday", "everyone", "everything", "everywhere", "evidence", "evolution", 
        "evolve", "exact", "exactly", "examination", "examine", "example", "exceed", "excellent", "except", 
        "exception", "exchange", "exciting", "executive", "exercise", "exhibit", "exhibition", "exist", "existence", 
        "existing", "expand", "expansion", "expect", "expectation", "expense", "expensive", "experience", 
        "experiment", "expert", "explain", "explanation", "explode", "explore", "explosion", "expose", "exposure", 
        "express", "expression", "extend", "extension", "extensive", "extent", "external", "extra", "extraordinary",
        "extreme", "extremely", "eye", "fabric", "face", "facility", "fact", "factor", "factory", "faculty", 
        "fade", "fail", "failure", "fair", "fairly", "faith", "fall", "false", "familiar", "family", "famous", 
        "fan", "fantasy", "far", "farm", "farmer", "fashion", "fast", "fat", "fate", "father", "fault", "favor", 
        "favorite", "fear", "feature", "federal", "fee", "feed", "feel", "feeling", "fellow", "female", "fence", 
        "few", "fewer", "fiber", "fiction", "field", "fifteen", "fifth", "fifty", "fight", "fighter", "fighting", 
        "figure", "file", "fill", "film", "final", "finally", "finance", "financial", "find", "finding", "fine", 
        "finger", "finish", "fire", "firm", "first", "fish", "fishing", "fit", "fitness", "five", "fix", "flag", 
        "flame", "flat", "flavor", "flee", "flesh", "flight", "float", "floor", "flow", "flower", "fly", "focus", 
        "folk", "follow", "following", "food", "foot", "football", "for", "force", "foreign", "forest", "forever", 
        "forget", "form", "formal", "formation", "former", "formula", "forth", "fortune", "forward", "found", 
        "foundation", "founder", "four", "fourth", "frame", "framework", "free", "freedom", "freeze", "french", 
        "frequency", "frequent", "frequently", "fresh", "friend", "friendly", "friendship", "from", "front", "fruit", 
        "frustration", "fuel", "full", "fully", "fun", "function", "fund", "fundamental", "funding", "funeral", "funny", 
        "furniture", "furthermore", "future", "gain", "galaxy", "gallery", "game", "gang", "gap", "garage", "garden", 
        "garlic", "gas", "gate", "gather", "gay", "gaze", "gear", "gender", "gene", "general", "generally", "generate", 
        "generation", "genetic", "gentleman", "gently", "german", "gesture", "get", "ghost", "giant", "gift", "gifted", 
        "girl", "girlfriend", "give", "given", "glad", "glance", "glass", "global", "glove", "go", "goal", "god", "gold", 
        "golden", "golf", "good", "government", "governor", "grab", "grade", "gradually", "graduate", "grain", "grand", 
        "grandfather", "grandmother", "grant", "grass", "grave", "gray", "great", "greatest", "green", "grocery", 
        "ground", "group", "grow", "growing", "growth", "guarantee", "guard", "guess", "guest", "guide", "guideline", 
        "guilty", "gun", "guy", "habit", "habitat", "hair", "half", "hall", "hand", "handful", "handle", "hang", "happen", 
        "happy", "hard", "hardly", "hat", "hate", "have", "he", "head", "headline", "headquarters", "health", "healthy", 
        "hear", "hearing", "heart", "heat", "heaven", "heavily", "heavy", "heel", "height", "helicopter", "hell", "hello", 
        "help", "helpful", "her", "here", "heritage", "hero", "herself", "hey", "hi", "hide", "high", "highlight", "highly", 
        "highway", "hill", "him", "himself", "hip", "hire", "his", "historian", "historic", "historical", "history", "hit", 
        "hold", "hole", "holiday", "holy", "home", "homeless", "honest", "honey", "honor", "hope", "horizon", "horror", 
        "horse", "hospital", "host", "hot", "hotel", "hour", "house", "household", "housing", "how", "however", "huge", 
        "human", "humor", "hundred", "hungry", "hunter", "hunting", "hurt", "husband", "hypothesis", "i", "ice", "idea", 
        "ideal", "identification", "identify", "identity", "ie", "if", "ignore", "ill", "illegal", "illness", "illustrate", 
        "image", "imagination", "imagine", "immediate", "immediately", "immigrant", "immigration", "impact", "implement", 
        "implication", "imply", "importance", "important", "impose", "impossible", "impress", "impression", "impressive", 
        "improve", "improvement", "in", "incentive", "incident", "include", "including", "income", "incorporate", "increase", 
        "increased", "increasing", "increasingly", "incredible", "indeed", "independence", "independent", "index", "indian", 
        "indicate", "indication", "individual", "industrial", "industry", "infant", "infection", "inflation", "influence", 
        "inform", "information", "ingredient", "initial", "initially", "initiative", "injury", "inner", "innocent", "inquiry",
        "inside", "insight", "insist", "inspire", "install", "instance", "instead", "institution", "institutional", 
        "instruction", "instructor", "instrument", "insurance", "intellectual", "intelligence", "intend", "intense", 
        "intensity", "intention", "interaction", "interest", "interested", "interesting", "internal", "international", 
        "internet", "interpret", "interpretation", "intervention", "interview", "into", "introduce", "introduction", 
        "invasion", "invest", "investigate", "investigation", "investigator", "investment", "investor", "invite", "involve", 
        "involved", "involvement", "iraqi", "irish", "iron", "islamic", "island", "israeli", "issue", "it", "italian", "item", 
        "its", "itself", "jacket", "jail", "japanese", "jet", "jew", "jewish", "job", "join", "joint", "joke", "journal", 
        "journalist", "journey", "joy", "judge", "judgment", "juice", "jump", "junior", "jury", "just", "justice", "justify", 
        "keep", "key", "kick", "kid", "kill", "killer", "killing", "kind", "king", "kiss", "kitchen", "knee", "knife", "knock", 
        "know", "knowledge", "lab", "label", "labor", "laboratory", "lack", "lady", "lake", "land", "landscape", "language", 
        "lap", "large", "largely", "last", "late", "later", "latin", "latter", "laugh", "launch", "law", "lawn", "lawsuit", 
        "lawyer", "lay", "layer", "lead", "leader", "leadership", "leading", "leaf", "league", "lean", "learn", "learning", 
        "least", "leather", "leave", "left", "leg", "legacy", "legal", "legend", "legislation", "legitimate", "lemon", "length", 
        "less", "lesson", "let", "letter", "level", "liberal", "library", "license", "lie", "life", "lifestyle", "lifetime", 
        "lift", "light", "like", "likely", "limit", "limitation", "limited", "line", "link", "lip", "list", "listen", "literally", 
        "literary", "literature", "little", "live", "living", "load", "loan", "local", "locate", "location", "lock", "long", 
        "long-term", "look", "loose", "lose", "loss", "lost", "lot", "lots", "loud", "love", "lovely", "lover", "low", 
        "lower", "luck", "lucky", "lunch", "lung", "machine", "mad", "magazine", "mail", "main", "mainly", "maintain", 
        "maintenance", "major", "majority", "make", "maker", "makeup", "male", "mall", "man", "manage", "management", 
        "manager", "manner", "manufacturer", "manufacturing", "many", "map", "margin", "mark", "market", "marketing", 
        "marriage", "married", "marry", "mask", "mass", "massive", "master", "match", "material", "math", "matter", 
        "may", "maybe", "mayor", "me", "meal", "mean", "meaning", "meanwhile", "measure", "measurement", "meat", 
        "mechanism", "media", "medical", "medication", "medicine", "medium", "meet", "meeting", "member", "membership", 
        "memory", "mental", "mention", "menu", "mere", "merely", "mess", "message", "metal", "meter", "method", 
        "mexican", "middle", "might", "military", "milk", "million", "mind", "mine", "minister", "minor", "minority", 
        "minute", "miracle", "mirror", "miss", "missile", "mission", "mistake", "mix", "mixture", "mm-hmm", "mode", 
        "model", "moderate", "modern", "modest", "mom", "moment", "money", "monitor", "month", "mood", "moon", "moral", 
        "more", "moreover", "morning", "mortgage", "most", "mostly", "mother", "motion", "motivation", "motor", "mount", 
        "mountain", "mouse", "mouth", "move", "movement", "movie", "mr", "mrs", "ms", "much", "multiple", "murder", 
        "muscle", "museum", "music", "musical", "musician", "muslim", "must", "mutual", "my", "myself", "mystery", 
        "myth", "naked", "name", "narrative", "narrow", "nation", "national", "native", "natural", "naturally", 
        "nature", "near", "nearby", "nearly", "necessarily", "necessary", "neck", "need", "negative", "negotiate", 
        "negotiation", "neighbor", "neighborhood", "neither", "nerve", "nervous", "net", "network", "never", "nevertheless", 
        "new", "newly", "news", "newspaper", "next", "nice", "night", "nine", "no", "nobody", "nod", "noise", "nomination", 
        "none", "nonetheless", "nor", "normal", "normally", "north", "northern", "nose", "not", "note", "nothing", 
        "notice", "notion", "novel", "now", "nowhere", "nuclear", "number", "numerous", "nurse", "nut", "object", 
        "objective", "obligation", "observation", "observe", "observer", "obtain", "obvious", "obviously", "occasion", 
        "occasionally", "occupation", "occupy", "occur", "ocean", "odd", "odds", "of", "off", "offense", "offensive", 
        "offer", "office", "officer", "official", "often", "oh", "oil", "ok", "okay", "old", "olympic", "on", "once", 
        "one", "ongoing", "onion", "online", "only", "onto", "open", "opening", "operate", "operating", "operation", 
        "operator", "opinion", "opponent", "opportunity", "oppose", "opposite", "opposition", "option", "or", 
        "orange", "order", "ordinary", "organic", "organization", "organize", "orientation", "origin", "original", 
        "originally", "other", "others", "otherwise", "ought", "our", "ourselves", "out", "outcome", "outside", 
        "oven", "over", "overall", "overcome", "overlook", "owe", "own", "owner", "pace", "pack", "package", "page", 
        "pain", "painful", "paint", "painter", "painting", "pair", "pale", "palestinian", "palm", "pan", "panel", 
        "pant", "paper", "parent", "park", "parking", "part", "participant", "participate", "participation", "particular", 
        "particularly", "partly", "partner", "partnership", "party", "pass", "passage", "passenger", "passion", "past", 
        "patch", "path", "patient", "pattern", "pause", "pay", "payment", "pc", "peace", "peak", "peer", "penalty", 
        "people", "pepper", "per", "perceive", "percentage", "perception", "perfect", "perfectly", "perform", 
        "performance", "perhaps", "period", "permanent", "permission", "permit", "person", "personal", "personality", 
        "personally", "personnel", "perspective", "persuade", "pet", "phase", "phenomenon", "philosophy", "phone", 
        "photo", "photograph", "photographer", "phrase", "physical", "physically", "physician", "piano", "pick", 
        "picture", "pie", "piece", "pile", "pilot", "pine", "pink", "pipe", "pitch", "place", "plan", "plane", "planet", 
        "planning", "plant", "plastic", "plate", "platform", "play", "player", "please", "pleasure", "plenty", "plot", 
        "plus", "pm", "pocket", "poem", "poet", "poetry", "point", "pole", "police", "policy", "political", "politically", 
        "politician", "politics", "poll", "pollution", "pool", "poor", "pop", "popular", "population", "porch", "port", 
        "portion", "portrait", "portray", "pose", "position", "positive", "possess", "possibility", "possible", "possibly", 
        "post", "pot", "potato", "potential", "potentially", "pound", "pour", "poverty", "powder", "power", "powerful", 
        "practical", "practice", "pray", "prayer", "precisely", "predict", "prefer", "preference", "pregnancy", "pregnant", 
        "preparation", "prepare", "prescription", "presence", "present", "presentation", "preserve", "president", 
        "presidential", "press", "pressure", "pretend", "pretty", "prevent", "previous", "previously", "price", "pride", 
        "priest", "primarily", "primary", "prime", "principal", "principle", "print", "prior", "priority", "prison", 
        "prisoner", "privacy", "private", "probably", "problem", "procedure", "proceed", "process", "produce", "producer", 
        "product", "production", "profession", "professional", "professor", "profile", "profit", "program", "progress", 
        "project", "prominent", "promise", "promote", "prompt", "proof", "proper", "properly", "property", "proportion", 
        "proposal", "propose", "proposed", "prosecutor", "prospect", "protect", "protection", "protein", "protest", 
        "proud", "prove", "provide", "provider", "province", "provision", "psychological", "psychologist", "psychology", 
        "public", "publication", "publicly", "publish", "publisher", "pull", "punishment", "purchase", "pure", "purpose", 
        "pursue", "push", "put", "qualify", "quality", "quarter", "quarterback", "question", "quick", "quickly", "quiet", 
        "quietly", "quit", "quite", "quote", "race", "racial", "radical", "radio", "rail", "rain", "raise", "range", 
        "rank", "rapid", "rapidly", "rare", "rarely", "rate", "rather", "rating", "ratio", "raw", "reach", "react", 
        "reaction", "read", "reader", "reading", "ready", "real", "reality", "realize", "really", "reason", "reasonable", 
        "recall", "receive", "recent", "recently", "recipe", "recognition", "recognize", "recommend", "recommendation", 
        "record", "recording", "recover", "recovery", "recruit", "red", "reduce", "reduction", "refer", "reference", 
        "reflect", "reflection", "reform", "refugee", "refuse", "regard", "regarding", "regardless", "regime", "region", 
        "regional", "register", "regular", "regularly", "regulate", "regulation", "reinforce", "reject", "relate", 
        "relation", "relationship", "relative", "relatively", "relax", "release", "relevant", "relief", "religion", 
        "religious", "rely", "remain", "remaining", "remarkable", "remember", "remind", "remote", "remove", "repeat", 
        "repeatedly", "replace", "reply", "report", "reporter", "represent", "representation", "representative", 
        "republican", "reputation", "request", "require", "requirement", "research", "researcher", "resemble", 
        "reservation", "resident", "resist", "resistance", "resolution", "resolve", "resort", "resource", "respect", 
        "respond", "respondent", "response", "responsibility", "responsible", "rest", "restaurant", "restore", "restriction", 
        "result", "retain", "retire", "retirement", "return", "reveal", "revenue", "review", "revolution", "rhythm", "rice", 
        "rich", "rid", "ride", "rifle", "right", "ring", "rise", "risk", "river", "road", "rock", "role", "roll", "romantic", 
        "roof", "room", "root", "rope", "rose", "rough", "roughly", "round", "route", "routine", "row", "rub", "rule", "run", 
        "running", "rural", "rush", "russian", "sacred", "sad", "safe", "safety", "sake", "salad", "salary", "sale", "sales", 
        "salt", "same", "sample", "sanction", "sand", "satellite", "satisfaction", "satisfy", "sauce", "save", "saving", 
        "say", "scale", "scandal", "scared", "scenario", "scene", "schedule", "scheme", "scholar", "scholarship", "school", 
        "science", "scientific", "scientist", "scope", "score", "scream", "screen", "script", "sea", "search", "season", 
        "seat", "second", "secret", "secretary", "section", "sector", "secure", "security", "see", "seed", "seek", "seem", 
        "segment", "seize", "select", "selection", "self", "sell", "senate", "senator", "send", "senior", "sense", 
        "sensitive", "sentence", "separate", "sequence", "series", "serious", "seriously", "serve", "service", "session", 
        "set", "setting", "settle", "settlement", "seven", "several", "severe", "sex", "sexual", "shade", "shadow", 
        "shake", "shall", "shape", "share", "sharp", "she", "sheet", "shelf", "shell", "shelter", "shift", "shine", "ship", 
        "shirt", "shit", "shock", "shoe", "shoot", "shooting", "shop", "shopping", "shore", "short", "shortly", "shot",
        "should", "shoulder", "shout", "show", "shower", "shrug", "shut", "sick", "side", "sigh", "sight", "sign", "signal", 
        "significance", "significant", "significantly", "silence", "silent", "silver", "similar", "similarly", "simple", 
        "simply", "sin", "since", "sing", "singer", "single", "sink", "sir", "sister", "sit", "site", "situation", "six", 
        "size", "ski", "skill", "skin", "sky", "slave", "sleep", "slice", "slide", "slight", "slightly", "slip", "slow", 
        "slowly", "small", "smart", "smell", "smile", "smoke", "smooth", "snap", "snow", "so", "so-called", "soccer", 
        "social", "society", "soft", "software", "soil", "solar", "soldier", "solid", "solution", "solve", "some", 
        "somebody", "somehow", "someone", "something", "sometimes", "somewhat", "somewhere", "son", "song", "soon", 
        "sophisticated", "sorry", "sort", "soul", "sound", "soup", "source", "south", "southern", "soviet", "space", 
        "spanish", "speak", "speaker", "special", "specialist", "species", "specific", "specifically", "speech", "speed", 
        "spend", "spending", "spin", "spirit", "spiritual", "split", "spokesman", "sport", "spot", "spread", "spring", 
        "square", "squeeze", "stability", "stable", "staff", "stage", "stair", "stake", "stand", "standard", "standing", 
        "star", "stare", "start", "state", "statement", "station", "statistics", "status", "stay", "steady", "steal", 
        "steel", "step", "stick", "still", "stir", "stock", "stomach", "stone", "stop", "storage", "store", "storm", "story", 
        "straight", "strange", "stranger", "strategic", "strategy", "stream", "street", "strength", "strengthen", "stress", 
        "stretch", "strike", "string", "strip", "stroke", "strong", "strongly", "structure", "struggle", "student", "studio", 
        "study", "stuff", "stupid", "style", "subject", "submit", "subsequent", "substance", "substantial", "succeed",
        "success", "successful", "successfully", "such", "sudden", "suddenly", "sue", "suffer", "sufficient", "sugar", 
        "suggest", "suggestion", "suicide", "suit", "summer", "summit", "sun", "super", "supply", "support", "supporter", 
        "suppose", "supposed", "supreme", "sure", "surely", "surface", "surgery", "surprise", "surprised", "surprising", 
        "surprisingly", "surround", "survey", "survival", "survive", "survivor", "suspect", "sustain", "swear", "sweep", 
        "sweet", "swim", "swing", "switch", "symbol", "symptom", "system", "table", "tablespoon", "tactic", "tail", "take", 
        "tale", "talent", "talk", "tall", "tank", "tap", "tape", "target", "task", "taste", "tax", "taxpayer", "tea", "teach", 
        "teacher", "teaching", "team", "tear", "teaspoon", "technical", "technique", "technology", "teen", "teenager", 
        "telephone", "telescope", "television", "tell", "temperature", "temporary", "ten", "tend", "tendency", "tennis", 
        "tension", "tent", "term", "terms", "terrible", "territory", "terror", "terrorism", "terrorist", "test", "testify", 
        "testimony", "testing", "text", "than", "thank", "thanks", "that", "the", "theater", "their", "them", "theme", 
        "themselves", "then", "theory", "therapy", "there", "therefore", "these", "they", "thick", "thin", "thing", "think", 
        "thinking", "third", "thirty", "this", "those", "though", "thought", "thousand", "threat", "threaten", "three", 
        "throat", "through", "throughout", "throw", "thus", "ticket", "tie", "tight", "time", "tiny", "tip", "tire", 
        "tired", "tissue", "title", "to", "tobacco", "today", "toe", "together", "tomato", "tomorrow", "tone", "tongue", 
        "tonight", "too", "tool", "tooth", "top", "topic", "toss", "total", "totally", "touch", "tough", "tour", "tourist", 
        "tournament", "toward", "towards", "tower", "town", "toy", "trace", "track", "trade", "tradition", "traditional", 
        "traffic", "tragedy", "trail", "train", "training", "transfer", "transform", "transformation", "transition", 
        "translate", "transportation", "travel", "treat", "treatment", "treaty", "tree", "tremendous", "trend", 
        "trial", "tribe", "trick", "trip", "troop", "trouble", "truck", "true", "truly", "trust", "truth", "try", 
        "tube", "tunnel", "turn", "tv", "twelve", "twenty", "twice", "twin", "two", "type", "typical", "typically", 
        "ugly", "ultimate", "ultimately", "unable", "uncle", "under", "undergo", "understand", "understanding", 
        "unfortunately", "uniform", "union", "unique", "unit", "united", "universal", "universe", "university", 
        "unknown", "unless", "unlike", "unlikely", "until", "unusual", "up", "upon", "upper", "urban", "urge", 
        "us", "use", "used", "useful", "user", "usual", "usually", "utility", "vacation", "valley", "valuable", 
        "value", "variable", "variation", "variety", "various", "vary", "vast", "vegetable", "vehicle", 
        "venture", "version", "versus", "very", "vessel", "veteran", "via", "victim", "victory", "video", 
        "view", "viewer", "village", "violate", "violation", "violence", "violent", "virtually", "virtue", 
        "virus", "visible", "vision", "visit", "visitor", "visual", "vital", "voice", "volume", "volunteer", 
        "vote", "voter", "vs", "vulnerable", "wage", "wait", "wake", "walk", "wall", "wander", "want", 
        "war", "warm", "warn", "warning", "wash", "waste", "watch", "water", "wave", "way", "we", 
        "weak", "wealth", "wealthy", "weapon", "wear", "weather", "wedding", "week", "weekend", 
        "weekly", "weigh", "weight", "welcome", "welfare", "well", "west", "western", "wet", 
        "what", "whatever", "wheel", "when", "whenever", "where", "whereas", "whether", 
        "which", "while", "whisper", "white", "who", "whole", "whom", "whose", "why", "wide", 
        "widely", "widespread", "wife", "wild", "will", "willing", "win", "wind", "window", 
        "wine", "wing", "winner", "winter", "wipe", "wire", "wisdom", "wise", "wish", "with", 
        "withdraw", "within", "without", "witness", "woman", "wonder", "wonderful", "wood", 
        "wooden", "word", "work", "worker", "working", "works", "workshop", "world", 
        "worried", "worry", "worth", "would", "wound", "wrap", "write", "writer", "writing", 
        "wrong", "yard", "yeah", "year", "yell", "yellow", "yes", "yesterday", "yet", "yield", 
        "you", "young", "your", "yours", "yourself", "youth", "zone"]

EASY = ['act', 'ad', 'add', 'age', 'ago', 'ah', 'aid', 'aim', 'air', 'all', 'am', 'and', 'any', 'arm', 'art', 'as', 'ask', 'at', 'bad', 'bag', 'ban', 'bar', 'be', 'bed', 'bet', 'big', 'bit', 'box', 'boy', 'bus', 'but', 'buy', 'by', 'can', 'cap', 'car', 'cat', 'ceo', 'cop', 'cow', 'cry', 'cup', 'cut', 'dad', 'day', 'die', 'dig', 'dna', 'do', 'dog', 'dry', 'due', 'ear', 'eat', 'egg', 'end', 'era', 'etc', 'eye', 'fan', 'far', 'fat', 'fee', 'few', 'fit', 'fix', 'fly', 'for', 'fun', 'gap', 'gas', 'gay', 'get', 'go', 'god', 'gun', 'guy', 'hat', 'he', 'her', 'hey', 'hi', 'him', 'hip', 'his', 'hit', 'hot', 'how', 'i', 'ice', 'ie', 'if', 'ill', 'in', 'it', 'its', 'jet', 'jew', 'job', 'joy', 'key', 'kid', 'lab', 'lap', 'law', 'lay', 'leg', 'let', 'lie', 'lip', 'lot', 'low', 'mad', 'man', 'map', 'may', 'me', 'mix', 'mom', 'mr', 'mrs', 'ms', 'my', 'net', 'new', 'no', 'nod', 'nor', 'not', 'now', 'nut', 'odd', 'of', 'off', 'oh', 'oil', 'ok', 'old', 'on', 'one', 'or', 'our', 'out', 'owe', 'own', 'pan', 'pay', 'pc', 'per', 'pet', 'pie', 'pm', 'pop', 'pot', 'put', 'raw', 'red', 'rid', 'row', 'rub', 'run', 'sad', 'say', 'sea', 'see', 'set', 'sex', 'she', 'sin', 'sir', 'sit', 'six', 'ski', 'sky', 'so', 'son', 'sue', 'sun', 'tap', 'tax', 'tea', 'ten', 'the', 'tie', 'tip', 'to', 'toe', 'too', 'top', 'toy', 'try', 'tv', 'two', 'up', 'us', 'use', 'via', 'vs', 'war', 'way', 'we', 'wet', 'who', 'why', 'win', 'yes', 'yet', 'you']
MEDIUM = ['able', 'about', 'above', 'abroad', 'absorb', 'abuse', 'accept', 'access', 'accuse', 'acid', 'across', 'action', 'active', 'actor', 'actual', 'adapt', 'adjust', 'admire', 'admit', 'adopt', 'adult', 'advice', 'advise', 'affair', 'affect', 'afford', 'afraid', 'after', 'again', 'agency', 'agenda', 'agent', 'agree', 'ahead', 'aide', 'aids', 'album', 'alive', 'allow', 'ally', 'almost', 'alone', 'along', 'also', 'alter', 'always', 'among', 'amount', 'anger', 'angle', 'angry', 'animal', 'annual', 'answer', 'anyone', 'anyway', 'apart', 'appeal', 'appear', 'apple', 'apply', 'arab', 'area', 'argue', 'arise', 'armed', 'army', 'around', 'arrest', 'arrive', 'artist', 'asian', 'aside', 'asleep', 'aspect', 'assert', 'assess', 'asset', 'assign', 'assist', 'assume', 'assure', 'attach', 'attack', 'attend', 'author', 'auto', 'avoid', 'award', 'aware', 'away', 'awful', 'baby', 'back', 'badly', 'bake', 'ball', 'band', 'bank', 'barely', 'barrel', 'base', 'basic', 'basis', 'basket', 'battle', 'beach', 'bean', 'bear', 'beat', 'beauty', 'become', 'beer', 'before', 'begin', 'behind', 'being', 'belief', 'bell', 'belong', 'below', 'belt', 'bench', 'bend', 'beside', 'best', 'better', 'beyond', 'bible', 'bike', 'bill', 'bind', 'bird', 'birth', 'bite', 'black', 'blade', 'blame', 'blind', 'block', 'blood', 'blow', 'blue', 'board', 'boat', 'body', 'bomb', 'bond', 'bone', 'book', 'boom', 'boot', 'border', 'born', 'borrow', 'boss', 'both', 'bother', 'bottle', 'bottom', 'bowl', 'brain', 'branch', 'brand', 'bread', 'break', 'breast', 'breath', 'brick', 'bridge', 'brief', 'bright', 'bring', 'broad', 'broken', 'brown', 'brush', 'buck', 'budget', 'build', 'bullet', 'bunch', 'burden', 'burn', 'bury', 'busy', 'butter', 'button', 'buyer', 'cabin', 'cable', 'cake', 'call', 'camera', 'camp', 'campus', 'cancer', 'carbon', 'card', 'care', 'career', 'carry', 'case', 'cash', 'cast', 'catch', 'cause', 'cell', 'center', 'chain', 'chair', 'chance', 'change', 'charge', 'chart', 'chase', 'cheap', 'check', 'cheek', 'cheese', 'chef', 'chest', 'chief', 'child', 'chip', 'choice', 'choose', 'church', 'circle', 'cite', 'city', 'civil', 'claim', 'class', 'clean', 'clear', 'client', 'climb', 'clinic', 'clock', 'close', 'closer', 'cloud', 'club', 'clue', 'coach', 'coal', 'coast', 'coat', 'code', 'coffee', 'cold', 'color', 'column', 'come', 'comedy', 'commit', 'common', 'cook', 'cookie', 'cool', 'cope', 'copy', 'core', 'corn', 'corner', 'cost', 'cotton', 'couch', 'could', 'count', 'county', 'couple', 'course', 'court', 'cousin', 'cover', 'crack', 'craft', 'crash', 'crazy', 'cream', 'create', 'credit', 'crew', 'crime', 'crisis', 'critic', 'crop', 'cross', 'crowd', 'custom', 'cycle', 'daily', 'damage', 'dance', 'danger', 'dare', 'dark', 'data', 'date', 'dead', 'deal', 'dealer', 'dear', 'death', 'debate', 'debt', 'decade', 'decide', 'deck', 'deep', 'deeply', 'deer', 'defeat', 'defend', 'define', 'degree', 'delay', 'demand', 'deny', 'depend', 'depict', 'depth', 'deputy', 'derive', 'desert', 'design', 'desire', 'desk', 'detail', 'detect', 'device', 'devote', 'diet', 'differ', 'dining', 'dinner', 'direct', 'dirt', 'dirty', 'dish', 'divide', 'doctor', 'door', 'double', 'doubt', 'down', 'dozen', 'draft', 'drag', 'drama', 'draw', 'dream', 'dress', 'drink', 'drive', 'driver', 'drop', 'drug', 'during', 'dust', 'duty', 'each', 'eager', 'early', 'earn', 'earth', 'ease', 'easily', 'east', 'easy', 'edge', 'editor', 'effect', 'effort', 'eight', 'either', 'elect', 'elite', 'else', 'e-mail', 'emerge', 'employ', 'empty', 'enable', 'enemy', 'energy', 'engage', 'engine', 'enjoy', 'enough', 'ensure', 'enter', 'entire', 'entry', 'equal', 'error', 'escape', 'essay', 'estate', 'ethics', 'ethnic', 'even', 'event', 'ever', 'every', 'evolve', 'exact', 'exceed', 'except', 'exist', 'expand', 'expect', 'expert', 'expose', 'extend', 'extent', 'extra', 'fabric', 'face', 'fact', 'factor', 'fade', 'fail', 'fair', 'fairly', 'faith', 'fall', 'false', 'family', 'famous', 'farm', 'farmer', 'fast', 'fate', 'father', 'fault', 'favor', 'fear', 'feed', 'feel', 'fellow', 'female', 'fence', 'fewer', 'fiber', 'field', 'fifth', 'fifty', 'fight', 'figure', 'file', 'fill', 'film', 'final', 'find', 'fine', 'finger', 'finish', 'fire', 'firm', 'first', 'fish', 'five', 'flag', 'flame', 'flat', 'flavor', 'flee', 'flesh', 'flight', 'float', 'floor', 'flow', 'flower', 'focus', 'folk', 'follow', 'food', 'foot', 'force', 'forest', 'forget', 'form', 'formal', 'former', 'forth', 'found', 'four', 'fourth', 'frame', 'free', 'freeze', 'french', 'fresh', 'friend', 'from', 'front', 'fruit', 'fuel', 'full', 'fully', 'fund', 'funny', 'future', 'gain', 'galaxy', 'game', 'gang', 'garage', 'garden', 'garlic', 'gate', 'gather', 'gaze', 'gear', 'gender', 'gene', 'gently', 'german', 'ghost', 'giant', 'gift', 'gifted', 'girl', 'give', 'given', 'glad', 'glance', 'glass', 'global', 'glove', 'goal', 'gold', 'golden', 'golf', 'good', 'grab', 'grade', 'grain', 'grand', 'grant', 'grass', 'grave', 'gray', 'great', 'green', 'ground', 'group', 'grow', 'growth', 'guard', 'guess', 'guest', 'guide', 'guilty', 'habit', 'hair', 'half', 'hall', 'hand', 'handle', 'hang', 'happen', 'happy', 'hard', 'hardly', 'hate', 'have', 'head', 'health', 'hear', 'heart', 'heat', 'heaven', 'heavy', 'heel', 'height', 'hell', 'hello', 'help', 'here', 'hero', 'hide', 'high', 'highly', 'hill', 'hire', 'hold', 'hole', 'holy', 'home', 'honest', 'honey', 'honor', 'hope', 'horror', 'horse', 'host', 'hotel', 'hour', 'house', 'huge', 'human', 'humor', 'hungry', 'hunter', 'hurt', 'idea', 'ideal', 'ignore', 'image', 'impact', 'imply', 'impose', 'income', 'indeed', 'index', 'indian', 'infant', 'inform', 'injury', 'inner', 'inside', 'insist', 'intend', 'into', 'invest', 'invite', 'irish', 'iron', 'island', 'issue', 'item', 'itself', 'jacket', 'jail', 'jewish', 'join', 'joint', 'joke', 'judge', 'juice', 'jump', 'junior', 'jury', 'just', 'keep', 'kick', 'kill', 'killer', 'kind', 'king', 'kiss', 'knee', 'knife', 'knock', 'know', 'label', 'labor', 'lack', 'lady', 'lake', 'land', 'large', 'last', 'late', 'later', 'latin', 'latter', 'laugh', 'launch', 'lawn', 'lawyer', 'layer', 'lead', 'leader', 'leaf', 'league', 'lean', 'learn', 'least', 'leave', 'left', 'legacy', 'legal', 'legend', 'lemon', 'length', 'less', 'lesson', 'letter', 'level', 'life', 'lift', 'light', 'like', 'likely', 'limit', 'line', 'link', 'list', 'listen', 'little', 'live', 'living', 'load', 'loan', 'local', 'locate', 'lock', 'long', 'look', 'loose', 'lose', 'loss', 'lost', 'lots', 'loud', 'love', 'lovely', 'lover', 'lower', 'luck', 'lucky', 'lunch', 'lung', 'mail', 'main', 'mainly', 'major', 'make', 'maker', 'makeup', 'male', 'mall', 'manage', 'manner', 'many', 'margin', 'mark', 'market', 'marry', 'mask', 'mass', 'master', 'match', 'math', 'matter', 'maybe', 'mayor', 'meal', 'mean', 'meat', 'media', 'medium', 'meet', 'member', 'memory', 'mental', 'menu', 'mere', 'merely', 'mess', 'metal', 'meter', 'method', 'middle', 'might', 'milk', 'mind', 'mine', 'minor', 'minute', 'mirror', 'miss', 'mm-hmm', 'mode', 'model', 'modern', 'modest', 'moment', 'money', 'month', 'mood', 'moon', 'moral', 'more', 'most', 'mostly', 'mother', 'motion', 'motor', 'mount', 'mouse', 'mouth', 'move', 'movie', 'much', 'murder', 'muscle', 'museum', 'music', 'muslim', 'must', 'mutual', 'myself', 'myth', 'naked', 'name', 'narrow', 'nation', 'native', 'nature', 'near', 'nearby', 'nearly', 'neck', 'need', 'nerve', 'never', 'newly', 'news', 'next', 'nice', 'night', 'nine', 'nobody', 'noise', 'none', 'normal', 'north', 'nose', 'note', 'notice', 'notion', 'novel', 'number', 'nurse', 'object', 'obtain', 'occupy', 'occur', 'ocean', 'odds', 'offer', 'office', 'often', 'okay', 'once', 'onion', 'online', 'only', 'onto', 'open', 'oppose', 'option', 'orange', 'order', 'origin', 'other', 'others', 'ought', 'oven', 'over', 'owner', 'pace', 'pack', 'page', 'pain', 'paint', 'pair', 'pale', 'palm', 'panel', 'pant', 'paper', 'parent', 'park', 'part', 'partly', 'party', 'pass', 'past', 'patch', 'path', 'pause', 'peace', 'peak', 'peer', 'people', 'pepper', 'period', 'permit', 'person', 'phase', 'phone', 'photo', 'phrase', 'piano', 'pick', 'piece', 'pile', 'pilot', 'pine', 'pink', 'pipe', 'pitch', 'place', 'plan', 'plane', 'planet', 'plant', 'plate', 'play', 'player', 'please', 'plenty', 'plot', 'plus', 'pocket', 'poem', 'poet', 'poetry', 'point', 'pole', 'police', 'policy', 'poll', 'pool', 'poor', 'porch', 'port', 'pose', 'post', 'potato', 'pound', 'pour', 'powder', 'power', 'pray', 'prayer', 'prefer', 'press', 'pretty', 'price', 'pride', 'priest', 'prime', 'print', 'prior', 'prison', 'profit', 'prompt', 'proof', 'proper', 'proud', 'prove', 'public', 'pull', 'pure', 'pursue', 'push', 'quick', 'quiet', 'quit', 'quite', 'quote', 'race', 'racial', 'radio', 'rail', 'rain', 'raise', 'range', 'rank', 'rapid', 'rare', 'rarely', 'rate', 'rather', 'rating', 'ratio', 'reach', 'react', 'read', 'reader', 'ready', 'real', 'really', 'reason', 'recall', 'recent', 'recipe', 'record', 'reduce', 'refer', 'reform', 'refuse', 'regard', 'regime', 'region', 'reject', 'relate', 'relax', 'relief', 'rely', 'remain', 'remind', 'remote', 'remove', 'repeat', 'reply', 'report', 'resist', 'resort', 'rest', 'result', 'retain', 'retire', 'return', 'reveal', 'review', 'rhythm', 'rice', 'rich', 'ride', 'rifle', 'right', 'ring', 'rise', 'risk', 'river', 'road', 'rock', 'role', 'roll', 'roof', 'room', 'root', 'rope', 'rose', 'rough', 'round', 'route', 'rule', 'rural', 'rush', 'sacred', 'safe', 'safety', 'sake', 'salad', 'salary', 'sale', 'sales', 'salt', 'same', 'sample', 'sand', 'sauce', 'save', 'saving', 'scale', 'scared', 'scene', 'scheme', 'school', 'scope', 'score', 'scream', 'screen', 'script', 'search', 'season', 'seat', 'second', 'secret', 'sector', 'secure', 'seed', 'seek', 'seem', 'seize', 'select', 'self', 'sell', 'senate', 'send', 'senior', 'sense', 'series', 'serve', 'settle', 'seven', 'severe', 'sexual', 'shade', 'shadow', 'shake', 'shall', 'shape', 'share', 'sharp', 'sheet', 'shelf', 'shell', 'shift', 'shine', 'ship', 'shirt', 'shit', 'shock', 'shoe', 'shoot', 'shop', 'shore', 'short', 'shot', 'should', 'shout', 'show', 'shower', 'shrug', 'shut', 'sick', 'side', 'sigh', 'sight', 'sign', 'signal', 'silent', 'silver', 'simple', 'simply', 'since', 'sing', 'singer', 'single', 'sink', 'sister', 'site', 'size', 'skill', 'skin', 'slave', 'sleep', 'slice', 'slide', 'slight', 'slip', 'slow', 'slowly', 'small', 'smart', 'smell', 'smile', 'smoke', 'smooth', 'snap', 'snow', 'soccer', 'social', 'soft', 'soil', 'solar', 'solid', 'solve', 'some', 'song', 'soon', 'sorry', 'sort', 'soul', 'sound', 'soup', 'source', 'south', 'soviet', 'space', 'speak', 'speech', 'speed', 'spend', 'spin', 'spirit', 'split', 'sport', 'spot', 'spread', 'spring', 'square', 'stable', 'staff', 'stage', 'stair', 'stake', 'stand', 'star', 'stare', 'start', 'state', 'status', 'stay', 'steady', 'steal', 'steel', 'step', 'stick', 'still', 'stir', 'stock', 'stone', 'stop', 'store', 'storm', 'story', 'stream', 'street', 'stress', 'strike', 'string', 'strip', 'stroke', 'strong', 'studio', 'study', 'stuff', 'stupid', 'style', 'submit', 'such', 'sudden', 'suffer', 'sugar', 'suit', 'summer', 'summit', 'super', 'supply', 'sure', 'surely', 'survey', 'swear', 'sweep', 'sweet', 'swim', 'swing', 'switch', 'symbol', 'system', 'table', 'tactic', 'tail', 'take', 'tale', 'talent', 'talk', 'tall', 'tank', 'tape', 'target', 'task', 'taste', 'teach', 'team', 'tear', 'teen', 'tell', 'tend', 'tennis', 'tent', 'term', 'terms', 'terror', 'test', 'text', 'than', 'thank', 'thanks', 'that', 'their', 'them', 'theme', 'then', 'theory', 'there', 'these', 'they', 'thick', 'thin', 'thing', 'think', 'third', 'thirty', 'this', 'those', 'though', 'threat', 'three', 'throat', 'throw', 'thus', 'ticket', 'tight', 'time', 'tiny', 'tire', 'tired', 'tissue', 'title', 'today', 'tomato', 'tone', 'tongue', 'tool', 'tooth', 'topic', 'toss', 'total', 'touch', 'tough', 'tour', 'toward', 'tower', 'town', 'trace', 'track', 'trade', 'trail', 'train', 'travel', 'treat', 'treaty', 'tree', 'trend', 'trial', 'tribe', 'trick', 'trip', 'troop', 'truck', 'true', 'truly', 'trust', 'truth', 'tube', 'tunnel', 'turn', 'twelve', 'twenty', 'twice', 'twin', 'type', 'ugly', 'unable', 'uncle', 'under', 'union', 'unique', 'unit', 'united', 'unless', 'unlike', 'until', 'upon', 'upper', 'urban', 'urge', 'used', 'useful', 'user', 'usual', 'valley', 'value', 'vary', 'vast', 'versus', 'very', 'vessel', 'victim', 'video', 'view', 'viewer', 'virtue', 'virus', 'vision', 'visit', 'visual', 'vital', 'voice', 'volume', 'vote', 'voter', 'wage', 'wait', 'wake', 'walk', 'wall', 'wander', 'want', 'warm', 'warn', 'wash', 'waste', 'watch', 'water', 'wave', 'weak', 'wealth', 'weapon', 'wear', 'week', 'weekly', 'weigh', 'weight', 'well', 'west', 'what', 'wheel', 'when', 'where', 'which', 'while', 'white', 'whole', 'whom', 'whose', 'wide', 'widely', 'wife', 'wild', 'will', 'wind', 'window', 'wine', 'wing', 'winner', 'winter', 'wipe', 'wire', 'wisdom', 'wise', 'wish', 'with', 'within', 'woman', 'wonder', 'wood', 'wooden', 'word', 'work', 'worker', 'works', 'world', 'worry', 'worth', 'would', 'wound', 'wrap', 'write', 'writer', 'wrong', 'yard', 'yeah', 'year', 'yell', 'yellow', 'yield', 'young', 'your', 'yours', 'youth', 'zone']
HARD = ['abandon', 'ability', 'abortion', 'absence', 'absolute', 'absolutely', 'academic', 'accident', 'accompany', 'accomplish', 'according', 'account', 'accurate', 'achieve', 'acquire', 'activist', 'activity', 'actress', 'actually', 'addition', 'additional', 'address', 'adequate', 'adjustment', 'admission', 'adolescent', 'advance', 'advanced', 'advantage', 'adventure', 'adviser', 'advocate', 'african', 'afternoon', 'against', 'aggressive', 'agreement', 'aircraft', 'airline', 'airport', 'alcohol', 'alliance', 'already', 'although', 'amazing', 'american', 'analysis', 'analyst', 'analyze', 'ancient', 'announce', 'another', 'anticipate', 'anxiety', 'anybody', 'anymore', 'anything', 'anywhere', 'apartment', 'apparent', 'apparently', 'appearance', 'appoint', 'appreciate', 'approach', 'approval', 'approve', 'architect', 'argument', 'arrange', 'arrival', 'article', 'artistic', 'assault', 'assessment', 'assignment', 'assistance', 'assistant', 'associate', 'assumption', 'athlete', 'athletic', 'atmosphere', 'attempt', 'attention', 'attitude', 'attorney', 'attract', 'attractive', 'attribute', 'audience', 'authority', 'available', 'average', 'awareness', 'background', 'balance', 'barrier', 'baseball', 'basically', 'basketball', 'bathroom', 'battery', 'beautiful', 'because', 'bedroom', 'beginning', 'behavior', 'believe', 'beneath', 'benefit', 'besides', 'between', 'billion', 'biological', 'birthday', 'blanket', 'bombing', 'boundary', 'boyfriend', 'breakfast', 'breathe', 'briefly', 'brilliant', 'british', 'brother', 'building', 'business', 'cabinet', 'calculate', 'campaign', 'canadian', 'candidate', 'capability', 'capable', 'capacity', 'capital', 'captain', 'capture', 'careful', 'carefully', 'carrier', 'category', 'catholic', 'ceiling', 'celebrate', 'celebrity', 'central', 'century', 'ceremony', 'certain', 'certainly', 'chairman', 'challenge', 'chamber', 'champion', 'changing', 'channel', 'chapter', 'character', 'charity', 'chemical', 'chicken', 'childhood', 'chinese', 'chocolate', 'christian', 'christmas', 'cigarette', 'citizen', 'civilian', 'classic', 'classroom', 'clearly', 'climate', 'clinical', 'closely', 'clothes', 'clothing', 'cluster', 'coalition', 'cognitive', 'collapse', 'colleague', 'collect', 'collection', 'collective', 'college', 'colonial', 'combine', 'comfort', 'command', 'commander', 'comment', 'commercial', 'commission', 'commitment', 'committee', 'community', 'company', 'compare', 'comparison', 'compete', 'competitor', 'complain', 'complaint', 'complete', 'completely', 'complex', 'component', 'compose', 'computer', 'concept', 'concern', 'concerned', 'concert', 'conclude', 'conclusion', 'concrete', 'condition', 'conduct', 'conference', 'confidence', 'confident', 'confirm', 'conflict', 'confront', 'confusion', 'congress', 'connect', 'connection', 'consensus', 'consider', 'consist', 'consistent', 'constant', 'constantly', 'constitute', 'construct', 'consultant', 'consume', 'consumer', 'contact', 'contain', 'container', 'content', 'contest', 'context', 'continue', 'continued', 'contract', 'contrast', 'contribute', 'control', 'convention', 'convert', 'conviction', 'convince', 'cooking', 'corporate', 'correct', 'council', 'counselor', 'counter', 'country', 'courage', 'coverage', 'creation', 'creative', 'creature', 'criminal', 'criteria', 'critical', 'criticism', 'criticize', 'crucial', 'cultural', 'culture', 'curious', 'current', 'currently', 'curriculum', 'customer', 'dangerous', 'darkness', 'daughter', 'decision', 'declare', 'decline', 'decrease', 'defendant', 'defense', 'defensive', 'deficit', 'definitely', 'definition', 'deliver', 'delivery', 'democracy', 'democrat', 'democratic', 'department', 'dependent', 'depending', 'depression', 'describe', 'deserve', 'designer', 'desperate', 'despite', 'destroy', 'detailed', 'determine', 'develop', 'developing', 'dialogue', 'difference', 'different', 'difficult', 'difficulty', 'digital', 'dimension', 'direction', 'directly', 'director', 'disability', 'disagree', 'disappear', 'disaster', 'discipline', 'discourse', 'discover', 'discovery', 'discuss', 'discussion', 'disease', 'dismiss', 'disorder', 'display', 'dispute', 'distance', 'distant', 'distinct', 'distribute', 'district', 'diverse', 'diversity', 'division', 'divorce', 'document', 'domestic', 'dominant', 'dominate', 'downtown', 'dramatic', 'drawing', 'earnings', 'eastern', 'economic', 'economics', 'economist', 'economy', 'edition', 'educate', 'education', 'educator', 'effective', 'efficiency', 'efficient', 'elderly', 'election', 'electric', 'electronic', 'element', 'elementary', 'eliminate', 'elsewhere', 'embrace', 'emergency', 'emission', 'emotion', 'emotional', 'emphasis', 'emphasize', 'employee', 'employer', 'employment', 'encounter', 'encourage', 'engineer', 'english', 'enhance', 'enormous', 'enterprise', 'entirely', 'entrance', 'episode', 'equally', 'equipment', 'especially', 'essential', 'establish', 'estimate', 'european', 'evaluate', 'evaluation', 'evening', 'eventually', 'everybody', 'everyday', 'everyone', 'everything', 'everywhere', 'evidence', 'evolution', 'exactly', 'examine', 'example', 'excellent', 'exception', 'exchange', 'exciting', 'executive', 'exercise', 'exhibit', 'exhibition', 'existence', 'existing', 'expansion', 'expense', 'expensive', 'experience', 'experiment', 'explain', 'explode', 'explore', 'explosion', 'exposure', 'express', 'expression', 'extension', 'extensive', 'external', 'extreme', 'extremely', 'facility', 'factory', 'faculty', 'failure', 'familiar', 'fantasy', 'fashion', 'favorite', 'feature', 'federal', 'feeling', 'fiction', 'fifteen', 'fighter', 'fighting', 'finally', 'finance', 'financial', 'finding', 'fishing', 'fitness', 'following', 'football', 'foreign', 'forever', 'formation', 'formula', 'fortune', 'forward', 'foundation', 'founder', 'framework', 'freedom', 'frequency', 'frequent', 'frequently', 'friendly', 'friendship', 'function', 'funding', 'funeral', 'furniture', 'gallery', 'general', 'generally', 'generate', 'generation', 'genetic', 'gentleman', 'gesture', 'girlfriend', 'government', 'governor', 'gradually', 'graduate', 'greatest', 'grocery', 'growing', 'guarantee', 'guideline', 'habitat', 'handful', 'headline', 'healthy', 'hearing', 'heavily', 'helicopter', 'helpful', 'heritage', 'herself', 'highlight', 'highway', 'himself', 'historian', 'historic', 'historical', 'history', 'holiday', 'homeless', 'horizon', 'hospital', 'household', 'housing', 'however', 'hundred', 'hunting', 'husband', 'hypothesis', 'identify', 'identity', 'illegal', 'illness', 'illustrate', 'imagine', 'immediate', 'immigrant', 'implement', 'importance', 'important', 'impossible', 'impress', 'impression', 'impressive', 'improve', 'incentive', 'incident', 'include', 'including', 'increase', 'increased', 'increasing', 'incredible', 'indicate', 'indication', 'individual', 'industrial', 'industry', 'infection', 'inflation', 'influence', 'ingredient', 'initial', 'initially', 'initiative', 'innocent', 'inquiry', 'insight', 'inspire', 'install', 'instance', 'instead', 'instructor', 'instrument', 'insurance', 'intense', 'intensity', 'intention', 'interest', 'interested', 'internal', 'internet', 'interpret', 'interview', 'introduce', 'invasion', 'investment', 'investor', 'involve', 'involved', 'islamic', 'israeli', 'italian', 'japanese', 'journal', 'journalist', 'journey', 'judgment', 'justice', 'justify', 'killing', 'kitchen', 'knowledge', 'laboratory', 'landscape', 'language', 'largely', 'lawsuit', 'leadership', 'leading', 'learning', 'leather', 'legitimate', 'liberal', 'library', 'license', 'lifestyle', 'lifetime', 'limitation', 'limited', 'literally', 'literary', 'literature', 'location', 'long-term', 'machine', 'magazine', 'maintain', 'majority', 'management', 'manager', 'marketing', 'marriage', 'married', 'massive', 'material', 'meaning', 'meanwhile', 'measure', 'mechanism', 'medical', 'medication', 'medicine', 'meeting', 'membership', 'mention', 'message', 'mexican', 'military', 'million', 'minister', 'minority', 'miracle', 'missile', 'mission', 'mistake', 'mixture', 'moderate', 'monitor', 'moreover', 'morning', 'mortgage', 'motivation', 'mountain', 'movement', 'multiple', 'musical', 'musician', 'mystery', 'narrative', 'national', 'natural', 'naturally', 'necessary', 'negative', 'negotiate', 'neighbor', 'neither', 'nervous', 'network', 'newspaper', 'nomination', 'normally', 'northern', 'nothing', 'nowhere', 'nuclear', 'numerous', 'objective', 'obligation', 'observe', 'observer', 'obvious', 'obviously', 'occasion', 'occupation', 'offense', 'offensive', 'officer', 'official', 'olympic', 'ongoing', 'opening', 'operate', 'operating', 'operation', 'operator', 'opinion', 'opponent', 'opposite', 'opposition', 'ordinary', 'organic', 'organize', 'original', 'originally', 'otherwise', 'ourselves', 'outcome', 'outside', 'overall', 'overcome', 'overlook', 'package', 'painful', 'painter', 'painting', 'parking', 'particular', 'partner', 'passage', 'passenger', 'passion', 'patient', 'pattern', 'payment', 'penalty', 'perceive', 'percentage', 'perception', 'perfect', 'perfectly', 'perform', 'perhaps', 'permanent', 'permission', 'personal', 'personally', 'personnel', 'persuade', 'phenomenon', 'philosophy', 'photograph', 'physical', 'physically', 'physician', 'picture', 'planning', 'plastic', 'platform', 'pleasure', 'political', 'politician', 'politics', 'pollution', 'popular', 'population', 'portion', 'portrait', 'portray', 'position', 'positive', 'possess', 'possible', 'possibly', 'potential', 'poverty', 'powerful', 'practical', 'practice', 'precisely', 'predict', 'preference', 'pregnancy', 'pregnant', 'prepare', 'presence', 'present', 'preserve', 'president', 'pressure', 'pretend', 'prevent', 'previous', 'previously', 'primarily', 'primary', 'principal', 'principle', 'priority', 'prisoner', 'privacy', 'private', 'probably', 'problem', 'procedure', 'proceed', 'process', 'produce', 'producer', 'product', 'production', 'profession', 'professor', 'profile', 'program', 'progress', 'project', 'prominent', 'promise', 'promote', 'properly', 'property', 'proportion', 'proposal', 'propose', 'proposed', 'prosecutor', 'prospect', 'protect', 'protection', 'protein', 'protest', 'provide', 'provider', 'province', 'provision', 'psychology', 'publicly', 'publish', 'publisher', 'punishment', 'purchase', 'purpose', 'qualify', 'quality', 'quarter', 'question', 'quickly', 'quietly', 'radical', 'rapidly', 'reaction', 'reading', 'reality', 'realize', 'reasonable', 'receive', 'recently', 'recognize', 'recommend', 'recording', 'recover', 'recovery', 'recruit', 'reduction', 'reference', 'reflect', 'reflection', 'refugee', 'regarding', 'regardless', 'regional', 'register', 'regular', 'regularly', 'regulate', 'regulation', 'reinforce', 'relation', 'relative', 'relatively', 'release', 'relevant', 'religion', 'religious', 'remaining', 'remarkable', 'remember', 'repeatedly', 'replace', 'reporter', 'represent', 'republican', 'reputation', 'request', 'require', 'research', 'researcher', 'resemble', 'resident', 'resistance', 'resolution', 'resolve', 'resource', 'respect', 'respond', 'respondent', 'response', 'restaurant', 'restore', 'retirement', 'revenue', 'revolution', 'romantic', 'roughly', 'routine', 'running', 'russian', 'sanction', 'satellite', 'satisfy', 'scandal', 'scenario', 'schedule', 'scholar', 'science', 'scientific', 'scientist', 'secretary', 'section', 'security', 'segment', 'selection', 'senator', 'sensitive', 'sentence', 'separate', 'sequence', 'serious', 'seriously', 'service', 'session', 'setting', 'settlement', 'several', 'shelter', 'shooting', 'shopping', 'shortly', 'shoulder', 'silence', 'similar', 'similarly', 'situation', 'slightly', 'so-called', 'society', 'software', 'soldier', 'solution', 'somebody', 'somehow', 'someone', 'something', 'sometimes', 'somewhat', 'somewhere', 'southern', 'spanish', 'speaker', 'special', 'specialist', 'species', 'specific', 'spending', 'spiritual', 'spokesman', 'squeeze', 'stability', 'standard', 'standing', 'statement', 'station', 'statistics', 'stomach', 'storage', 'straight', 'strange', 'stranger', 'strategic', 'strategy', 'strength', 'strengthen', 'stretch', 'strongly', 'structure', 'struggle', 'student', 'subject', 'subsequent', 'substance', 'succeed', 'success', 'successful', 'suddenly', 'sufficient', 'suggest', 'suggestion', 'suicide', 'support', 'supporter', 'suppose', 'supposed', 'supreme', 'surface', 'surgery', 'surprise', 'surprised', 'surprising', 'surround', 'survival', 'survive', 'survivor', 'suspect', 'sustain', 'symptom', 'tablespoon', 'taxpayer', 'teacher', 'teaching', 'teaspoon', 'technical', 'technique', 'technology', 'teenager', 'telephone', 'telescope', 'television', 'temporary', 'tendency', 'tension', 'terrible', 'territory', 'terrorism', 'terrorist', 'testify', 'testimony', 'testing', 'theater', 'themselves', 'therapy', 'therefore', 'thinking', 'thought', 'thousand', 'threaten', 'through', 'throughout', 'tobacco', 'together', 'tomorrow', 'tonight', 'totally', 'tourist', 'tournament', 'towards', 'tradition', 'traffic', 'tragedy', 'training', 'transfer', 'transform', 'transition', 'translate', 'treatment', 'tremendous', 'trouble', 'typical', 'typically', 'ultimate', 'ultimately', 'undergo', 'understand', 'uniform', 'universal', 'universe', 'university', 'unknown', 'unlikely', 'unusual', 'usually', 'utility', 'vacation', 'valuable', 'variable', 'variation', 'variety', 'various', 'vegetable', 'vehicle', 'venture', 'version', 'veteran', 'victory', 'village', 'violate', 'violation', 'violence', 'violent', 'virtually', 'visible', 'visitor', 'volunteer', 'vulnerable', 'warning', 'wealthy', 'weather', 'wedding', 'weekend', 'welcome', 'welfare', 'western', 'whatever', 'whenever', 'whereas', 'whether', 'whisper', 'widespread', 'willing', 'withdraw', 'without', 'witness', 'wonderful', 'working', 'workshop', 'worried', 'writing', 'yesterday', 'yourself']
