---
title: Possible Extension Ideas
sidebar: false
---

This project is perfect for those of you who are looking for a $+$ or (dare I say it) $++$ score, because there are so many possible extensions. Here are a few, but this list is by no means exhaustive!

  - _Add messages:_ The sample application on the website waits for the user to click the mouse before serving each ball and announces whether the player has won or lost at the end of the game. These are just `GLabel` objects that you can add and remove at the appropriate time.
  - _Improve the user control over bounces:_ The program gets rather boring if the only thing the player has to do is hit the ball. It is far more interesting if the player can control the ball some by hitting it at different parts of the paddle. In the old arcade game, the ball would bounce more horizontally if you hit it further from the center of the paddle.
  - _Add in a difficulty curve:_ The arcade version of Breakout lured you in by starting off slowly. But, as soon as you thought you were getting the hang of things, the program sped up, making life just a bit more exciting. If you start making the ball travel too fast here, your collision detection can start to struggle,
  - _Keep score: _ You could easily keep score, generating points for each brick broken. In the arcade game, bricks were more valuable higher up in the arrangement, so that you got more points for red bricks than for blue ones.
  - _Use your imagination!_ What else have you seen or always wanted a game like this to do?

