---
title: "Milestone 6: Reflection"
---

While you are all done with the coding, in this final project we are taking a moment to ask you to reflect on some potentially ethical considerations that may be present. This project is not unique in having some ethical facets around it, and in fact as programmers we always need to take some time to think about if the code we write or the ways we solve problems uphold the moral principles that govern (or ideally govern) society. 

Here, we have given at least some amount of creative control over storytelling to our code and the AI model. But is it as simple as that? Generative AI is an exciting new tool, but it comes with a lot of complicated questions. Is the AI doing a "good job"? Is the AI just copying stories from human content creators? What does it mean for our society if we can't tell the difference between AI content and human content? What values and biases does this generative AI have "baked in"? In this last milestone, we want to think and reflect a bit more about that last question.

Consider all of the choices you make when telling a story. Narratives, settings, and even names are all things that you, as a storyteller, get to decide. When we prompt our AI model, what choices is it making for us? Whose stories is it really telling?

Change the story name to `engineer_story`. This story has only a single pre-defined scene, and so it will start generating new scenes as soon as a user makes their first choice. Run the story a few times, playing through at least a handful of scenes each time, and write down the names that are generated for your co-workers. You can then explore the statistics behind any of the names generated using the website [here](https://forebears.io/forenames). Feel free to play around some with your own stories and to tweak the prompt or plot slightly as well. Then, answer the following questions in the `infinite_ethics.txt` file.

- Q1: You should notice that the names generated by OpenAI for this story are quite popular in certain countries. What types of countries/regions keep showing up for these names? Do you feel that they are distributed equally across the world population? Justify your answer, writing at least several sentences.

- Q2: How comfortable do you feel letting the AI model decide the names used in the story? Are you willing to trust the model with other storytelling decisions? There is no wrong position, but please justify your answer and write at least several sentences.

- Q3: Given how ChatGPT handled names in this context, what sorts of issues could you imagine coming up if instead of asking ChatGPT to generate a story, you were asking it to evaluate candidates for a job?

Make sure that when submitting your project, you also upload `infinite_ethics.txt`!
