<!DOCTYPE html>
<html lang="en"><head>
<script src="ch13.1_files/libs/clipboard/clipboard.min.js"></script>
<script src="ch13.1_files/libs/quarto-html/tabby.min.js"></script>
<script src="ch13.1_files/libs/quarto-html/popper.min.js"></script>
<script src="ch13.1_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="ch13.1_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ch13.1_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="ch13.1_files/libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.33">

  <meta name="author" content="Fred Agbo">
  <meta name="dcterms.date" content="2026-04-13">
  <title>TREES WITHIN GRAPHS</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="ch13.1_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="ch13.1_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="ch13.1_files/libs/revealjs/dist/theme/quarto-f563837468303362081e247dddd440d0.css">
  <link href="ch13.1_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="ch13.1_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="ch13.1_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="ch13.1_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="ch13.1_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="ch13.1_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">TREES WITHIN GRAPHS</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Fred Agbo 
</div>
</div>
</div>

  <p class="date">2026-04-13</p>
</section>
<section id="announcements" class="slide level2">
<h2>Announcements</h2>
<ul>
<li>Welcome to week 14!
<ul>
<li><code>Be encouraged despite the challenges!</code></li>
</ul></li>
<li>Mini Project #3 due date is extended to <strong><em>next week Monday April 20 at 10 pm</em></strong>.</li>
<li>Grading of PS4 and PS5 are published.</li>
<li>No class this Wednesday April 15. <code>It is SSRD Day!</code></li>
</ul>
</section>
<section id="trees-within-graphs" class="slide level2">
<h2>Trees within Graphs</h2>
<div style="font-size: 34px;">
<ul>
<li class="fragment">Recall the function <code>traverseFromVertex</code> shown in the Psedocode, it implicitly yields a tree rooted at the vertex from which the traversal starts and includes all the vertices reached during the traversal</li>
<li class="fragment">Suppose <code>dfs</code> has just been called using vertex <code>v</code>:
<ul>
<li class="fragment">If a recursive call using vertex <code>w</code> now occurs, you can consider <code>w</code> to be a child of <code>v</code> The edge <code>(v , w)</code> corresponds to the parent-child relationship, or edge, between <code>v</code> and <code>w</code></li>
<li class="fragment">The starting vertex is the root of this tree</li>
<li class="fragment">The tree is called a <code>depth-first search tree</code></li>
</ul></li>
</ul>
</div>
</section>
<section id="spanning-trees" class="slide level2">
<h2>Spanning Trees</h2>
<div style="font-size: 30px;">
<ul>
<li class="fragment">A <strong>spanning tree</strong> of a connected, undirected graph is a subgraph that includes all the vertices of the graph and is a tree.</li>
<li class="fragment">Every connected graph has at least one spanning tree.</li>
<li class="fragment">Spanning trees are useful for minimizing the number of edges while maintaining connectivity.</li>
<li class="fragment"><strong>Minimum Spanning Tree (MST):</strong> <!-- - A spanning tree with the smallest possible total edge weight.
    - Common algorithms for finding MSTs include Kruskal’s and Prim’s algorithms.--> <!-- - Applications include network design, clustering, and approximation algorithms.  --></li>
</ul>
</div>
</section>
<section id="minimum-spanning-tree" class="slide level2">
<h2>Minimum Spanning Tree</h2>
<div style="font-size: 30px;">
<ul>
<li class="fragment">A <strong>Minimum Spanning Tree (MST)</strong> is a spanning tree of a weighted, connected, undirected graph with the smallest possible total edge weight.</li>
<li class="fragment">MSTs are used in network design, clustering, and other optimization problems.</li>
<li class="fragment">Common algorithms for finding MSTs include Kruskal’s and Prim’s algorithms.-</li>
</ul>
</div>
</section>
<section id="minimum-spanning-tree-1" class="slide level2">
<h2>Minimum Spanning Tree</h2>
<div style="font-size: 26px;">
<ul>
<li class="fragment"><img data-src="../images/spanningTree2.png" style="width:80%;"></li>
<li class="fragment">The graph on the left has the maximum number of edges, <code>10</code>, for a five-vertex graph.</li>
<li class="fragment">The graph on the right has the same five vertices but with the minimum number of edges necessary to connect them, <code>4</code>.</li>
<li class="fragment">This constitutes a <code>minimum spanning tree (MST)</code> for the graph.</li>
</ul>
</div>
<aside class="notes">
<ul>
<li>DO YOU SEE ANY ALTERNATE PATH?</li>
<li>There are many possible minimum spanning trees (MSTs) for a given graph.</li>
<li>For example, the MST of the Figure above could include edges AC, BC, BD, and BE, or alternatively AC, CE, ED, and DB.</li>
<li>The number of edges in a minimum spanning tree is always one fewer than the number of vertices.</li>
<li>Removing any edge from a minimum spanning tree would create multiple connected components.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="minimum-spanning-tree-algorithms" class="slide level2">
<h2>Minimum Spanning Tree Algorithms</h2>
<div style="font-size: 30px;">
<ul>
<li class="fragment"><strong>Kruskal’s Algorithm:</strong>
<ul>
<li class="fragment">Sort all edges by weight.</li>
<li class="fragment">Add edges one by one to the tree, skipping those that would form a cycle, until all vertices are connected.</li>
</ul></li>
<li class="fragment"><strong>Prim’s Algorithm:</strong>
<ul>
<li class="fragment">Start from any vertex.</li>
<li class="fragment">Grow the tree by repeatedly adding the smallest edge that connects a vertex in the tree to a vertex outside.</li>
</ul></li>
<li class="fragment">Both algorithms run in <span class="math inline">\(O(E \log V)\)</span> time, where <span class="math inline">\(E\)</span> is the number of edges and <span class="math inline">\(V\)</span> is the number of vertices.</li>
</ul>
</div>
</section>
<section id="minimum-spanning-tree-2" class="slide level2">
<h2>Minimum Spanning Tree</h2>
<ul>
<li>Robert C. Prim’s <code>algorithm</code> for finding a minimum spanning tree</li>
</ul>
<div class="sourceCode" id="cb1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href=""></a>minimumSpanningTree(graph):</span>
<span id="cb1-2"><a href=""></a>    mark <span class="bu">all</span> vertices <span class="kw">and</span> edges <span class="im">as</span> unvisited</span>
<span id="cb1-3"><a href=""></a>    mark some vertex, say v, <span class="im">as</span> visited</span>
<span id="cb1-4"><a href=""></a>    <span class="cf">for</span> <span class="bu">all</span> the vertices:</span>
<span id="cb1-5"><a href=""></a>        find the least weight edge <span class="im">from</span> a visited vertex to an</span>
<span id="cb1-6"><a href=""></a>        unvisited vertex, say w</span>
<span id="cb1-7"><a href=""></a>        mark the edge <span class="kw">and</span> w <span class="im">as</span> visited</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="minimum-spanning-tree-3" class="slide level2">
<h2>Minimum Spanning Tree</h2>
<div style="font-size: 26px;">
<ul>
<li class="fragment"><p>Here is a weighted graph with six vertices. Each edge has a weight, shown by a number alongside the edge.</p></li>
<li class="fragment"><p><img data-src="../images/MSTExample1.png" style="width:40%;"></p></li>
<li class="fragment"><p>How can you pick a subgraph that minimizes the cost of connecting vertices into a network?</p></li>
</ul>
</div>
</section>
<section id="minimum-spanning-tree-4" class="slide level2">
<h2>Minimum Spanning Tree</h2>
<ul>
<li>The answer is to calculate a minimum spanning tree.</li>
<li>It will have five edges (one fewer than the number of vertices), it will connect all six vertices</li>
<li>It will minimize the total cost of the links.</li>
</ul>
</section>
<section id="recall-minimum-spanning-tree" class="slide level2">
<h2>Recall Minimum Spanning Tree</h2>
<div style="font-size: 26px;">
<ul>
<li class="fragment"><p>The MST for the graph above</p></li>
<li class="fragment"><p><img data-src="../images/MSTExample2.png" style="width:36%;"></p></li>
<li class="fragment"><p>The minimum spanning tree consists of the edges <code>AB</code>, <code>AC</code>, <code>CD</code>, <code>DE</code>, and <code>EF</code>, for a total edge weight of <code>28</code></p></li>
<li class="fragment"><p>The order in which the edges are specified is unimportant.</p></li>
</ul>
</div>
</section>
<section id="topological-sort" class="slide level2">
<h2>Topological Sort</h2>
<div style="font-size: 28px;">
<ul>
<li class="fragment">A topological sort of a directed acyclic graph (DAG) is a linear ordering of its vertices such that for every directed edge u → v, vertex u comes before v in the ordering.</li>
<li class="fragment">Topological sorting is useful for scheduling tasks, resolving dependencies, and organizing data with precedence constraints.</li>
<li class="fragment"><strong>Example Scenario:</strong>
<ul>
<li class="fragment">Imagine a university course catalog where each course may have prerequisites.</li>
<li class="fragment">Each course is a vertex, and a directed edge from course A to course B means “A is a prerequisite for B.”</li>
<li class="fragment">For example:
<ul>
<li class="fragment"><code>Math 101 → Math 201</code> (Math 101 is a prerequisite for Math 201)</li>
<li class="fragment"><code>CS 101 → CS 201</code> (CS 101 is a prerequisite for CS 201)</li>
<li class="fragment"><code>CS 201 → CS 301</code></li>
<li class="fragment"><code>Math 201 → CS 301</code></li>
</ul></li>
</ul></li>
<li class="fragment">Only DAGs have valid topological orders; graphs with cycles do not.</li>
</ul>
</div>
</section>
<section id="topological-sort-1" class="slide level2">
<h2>Topological Sort</h2>
<ul>
<li><img data-src="../images/graphOfCourses.png" style="width:50%;"></li>
</ul>
<div style="font-size: 25px;">
<ul>
<li class="fragment"><p>The first topological ordering of the graph</p></li>
<li class="fragment"><p><img data-src="../images/firstTopological.png" style="width:35%;"></p></li>
<li class="fragment"><p>The second topological ordering of the graph</p></li>
<li class="fragment"><p><img data-src="../images/secondTopological.png" style="width:35%;"></p></li>
</ul>
</div>
</section>
<section>
<section id="class-worksheet-activity" class="title-slide slide level1 center">
<h1>Class Worksheet Activity:</h1>

</section>
<section id="activity-1-spanning-tree-basics" class="slide level2">
<h2>Activity 1: Spanning Tree Basics</h2>
<div style="font-size: 28px;">
<p><strong>Question 1:</strong> A connected graph has 8 vertices. How many edges must its spanning tree have? Why?</p>
<p><strong>Question 2:</strong> True or False? A graph can have multiple different spanning trees. If true, provide an example scenario.</p>
<p><strong>Question 3:</strong> Can a disconnected graph have a spanning tree? Explain your reasoning.</p>
</div>
<aside class="notes">
<p><strong>Answer 1:</strong> 7 edges. A spanning tree for n vertices must have exactly n-1 edges. This is because a tree is a connected acyclic graph, and the minimum number of edges to connect n vertices without cycles is n-1.</p>
<p><strong>Answer 2:</strong> True. Most graphs have multiple spanning trees. Example: A triangle graph (3 vertices, 3 edges) has 3 different spanning trees - each one excludes a different edge. In the graph with vertices {A,B,C} and edges {AB, BC, AC}, you could have spanning trees: {AB, BC}, {AB, AC}, or {BC, AC}.</p>
<p><strong>Answer 3:</strong> No.&nbsp;A disconnected graph cannot have a spanning tree because a spanning tree must connect ALL vertices, and by definition, a disconnected graph has at least two components that cannot be reached from each other. However, each connected component can have its own spanning tree, forming a “spanning forest.”</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="activity-2-minimum-spanning-tree---prims-algorithm" class="slide level2">
<h2>Activity 2: Minimum Spanning Tree - Prim’s Algorithm</h2>
<div style="font-size: 26px;">
<p>Given the following weighted graph, apply <strong>Prim’s Algorithm</strong> starting from vertex A:</p>
<pre><code>    A ---5--- B
    |    \    |
    |     \   |
    3      7  6
    |       \ |
    C ---4--- D ---2--- E
         |             |
         8             1
         |             |
         F ------------</code></pre>
<p><strong>Tasks:</strong> 1. List the order in which edges are added to the MST 2. What is the total weight of the MST? 3. Draw the resulting MST</p>
</div>
<aside class="notes">
<p><strong>Answer:</strong> Starting from vertex A, Prim’s algorithm selects edges as follows:</p>
<ol type="1">
<li><strong>Edge A-C (weight 3)</strong> - cheapest edge from A</li>
<li><strong>Edge C-D (weight 4)</strong> - cheapest edge from {A,C} to unvisited vertices</li>
<li><strong>Edge D-E (weight 2)</strong> - cheapest edge from {A,C,D} to unvisited vertices</li>
<li><strong>Edge E-F (weight 1)</strong> - cheapest edge from {A,C,D,E} to unvisited vertices</li>
<li><strong>Edge A-B (weight 5)</strong> - only remaining vertex to connect</li>
</ol>
<p><strong>Total MST weight:</strong> 3 + 4 + 2 + 1 + 5 = <strong>15</strong></p>
<p><strong>MST edges:</strong> {A-C, C-D, D-E, E-F, A-B}</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="activity-3-mst-algorithm-comparison" class="slide level2">
<h2>Activity 3: MST Algorithm Comparison</h2>
<div style="font-size: 28px;">
<p><strong>Question 1:</strong> What is the key difference between Kruskal’s and Prim’s algorithm approaches?</p>
<p><strong>Question 2:</strong> Both algorithms have the same time complexity. What is it, and what do E and V represent?</p>
<p><strong>Question 3:</strong> When would you prefer Kruskal’s over Prim’s algorithm (or vice versa)?</p>
</div>
<aside class="notes">
<p><strong>Answer 1:</strong> - <strong>Kruskal’s Algorithm:</strong> Considers all edges globally, sorting them by weight and adding the cheapest edges that don’t create cycles (edge-based approach). - <strong>Prim’s Algorithm:</strong> Grows the MST from a starting vertex, repeatedly adding the cheapest edge that connects a vertex in the tree to a vertex outside (vertex-based approach).</p>
<p><strong>Answer 2:</strong> <strong>O(E log V)</strong> where: - <strong>E</strong> = number of edges in the graph - <strong>V</strong> = number of vertices in the graph - The log V factor comes from heap/priority queue operations or union-find operations</p>
<p><strong>Answer 3:</strong> - <strong>Prefer Kruskal’s when:</strong> The graph is sparse (few edges) or when edges are already sorted. Kruskal’s works well with edge lists and doesn’t require a specific starting vertex. - <strong>Prefer Prim’s when:</strong> The graph is dense (many edges) or stored as an adjacency matrix. Prim’s is often more efficient with dense graphs and works better with adjacency list representations.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="activity-4-topological-sort" class="slide level2">
<h2>Activity 4: Topological Sort</h2>
<div style="font-size: 26px;">
<p>Given the following course prerequisite graph:</p>
<ul>
<li class="fragment">CS 101 is a prerequisite for CS 201 and CS 202</li>
<li class="fragment">CS 201 is a prerequisite for CS 301</li>
<li class="fragment">CS 202 is a prerequisite for CS 301 and CS 302</li>
<li class="fragment">Math 101 is a prerequisite for CS 201</li>
<li class="fragment">Math 101 is a prerequisite for Math 201</li>
<li class="fragment">Math 201 is a prerequisite for CS 301</li>
</ul>
<p><strong>Tasks:</strong> 1. Draw the directed graph representing these dependencies 2. Provide at least TWO valid topological orderings 3. Explain why CS 301 cannot come before CS 201 in any valid ordering</p>
</div>
<aside class="notes">
<p><strong>Answer 1: Graph Structure</strong></p>
<pre><code>Math 101 → Math 201
    ↓           ↓
  CS 201 → CS 301
    ↑           ↑
CS 101 → CS 202 → CS 302</code></pre>
<p><strong>Answer 2: Valid Topological Orderings:</strong> 1. <strong>Math 101, CS 101, Math 201, CS 201, CS 202, CS 301, CS 302</strong> 2. <strong>CS 101, Math 101, CS 202, Math 201, CS 201, CS 301, CS 302</strong> 3. <strong>Math 101, CS 101, CS 202, Math 201, CS 201, CS 302, CS 301</strong></p>
<p>(Many other valid orderings exist)</p>
<p><strong>Answer 3:</strong> CS 301 cannot come before CS 201 because there is a directed path from CS 201 to CS 301, meaning CS 201 is a prerequisite (either directly or indirectly) for CS 301. In a valid topological ordering, all prerequisites must appear before the courses that depend on them. Specifically, CS 201 → CS 301 is a direct edge, so CS 201 MUST appear before CS 301.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="activity-5-cycle-detection" class="slide level2">
<h2>Activity 5: Cycle Detection</h2>
<div style="font-size: 30px;">
<p><strong>Question 1:</strong> Can a graph with a cycle have a valid topological sort? Why or why not?</p>
<p><strong>Question 2:</strong> Consider these course dependencies: - Course A requires Course B - Course B requires Course C<br>
- Course C requires Course A</p>
<p>What problem exists here? How would you detect this programmatically?</p>
</div>
<aside class="notes">
<p><strong>Answer 1:</strong> No, a graph with a cycle cannot have a valid topological sort. A topological ordering requires that for every directed edge u → v, vertex u must come before v. In a cycle, you would have vertices like A → B → C → A, which means A must come before B, B before C, and C before A - creating an impossible contradiction. Only Directed Acyclic Graphs (DAGs) can have topological orderings.</p>
<p><strong>Answer 2:</strong> <strong>Problem:</strong> This is a <strong>circular dependency</strong> (or cycle). Course A requires B, B requires C, and C requires A, forming a cycle A → B → C → A. This makes it impossible to determine which course to take first - you can never satisfy the prerequisites!</p>
<p><strong>Detection Methods:</strong> 1. <strong>DFS with colors:</strong> Use three states (white/unvisited, gray/visiting, black/visited). If you encounter a gray vertex during DFS, you’ve found a back edge indicating a cycle. 2. <strong>Topological sort attempt:</strong> Try to perform a topological sort using Kahn’s algorithm. If you can’t process all vertices (some remain with non-zero in-degree), a cycle exists. 3. <strong>Recursion stack:</strong> During DFS, maintain a recursion stack. If you visit a vertex already in the current recursion stack, there’s a cycle.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="activity-6-application-problem" class="slide level2">
<h2>Activity 6: Application Problem</h2>
<div style="font-size: 26px;">
<p><strong>Scenario:</strong> You are designing a network to connect 5 cities with fiber optic cables. The cost (in millions) to connect each pair of cities is:</p>
<ul>
<li class="fragment">City A to B: $4M, A to C: $3M, A to D: $7M</li>
<li class="fragment">City B to C: $2M, B to E: $5M</li>
<li class="fragment">City C to D: $4M, C to E: $6M<br>
</li>
<li class="fragment">City D to E: $3M</li>
</ul>
<p><strong>Tasks:</strong> 1. Which algorithm would you use to minimize total cost? Why? 2. Find the minimum cost to connect all cities 3. Which connections should be built? 4. What is the total cost of your solution?</p>
</div>
<aside class="notes">
<p><strong>Answer:</strong></p>
<p><strong>1. Algorithm Choice:</strong> Use either <strong>Kruskal’s or Prim’s algorithm</strong> to find the Minimum Spanning Tree. Either will give the same result. Kruskal’s might be slightly easier to trace manually since we can just sort edges by cost.</p>
<p><strong>2-4. Solution using Kruskal’s Algorithm:</strong></p>
<p>First, list all edges sorted by cost: 1. B-C: $2M 2. A-C: $3M<br>
3. D-E: $3M 4. A-B: $4M 5. C-D: $4M 6. B-E: $5M 7. C-E: $6M 8. A-D: $7M</p>
<p>Add edges that don’t create cycles: - ✓ Add B-C ($2M) - connects B and C - ✓ Add A-C ($3M) - connects A to {B,C} - ✓ Add D-E ($3M) - connects D and E - ✗ Skip A-B ($4M) - would create cycle A-C-B-A - ✓ Add C-D ($4M) - connects {A,B,C} to {D,E}</p>
<p>Now all 5 cities are connected with 4 edges (n-1).</p>
<p><strong>3. Connections to build:</strong> B-C, A-C, D-E, C-D</p>
<p><strong>4. Total cost:</strong> $2M + $3M + $3M + $4M = <strong>$12 million</strong></p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="bonus-challenge-dfs-tree" class="slide level2">
<h2>Bonus Challenge: DFS Tree</h2>
<div style="font-size: 28px;">
<p>Given an undirected graph with vertices {A, B, C, D, E, F} and edges: - A-B, A-C, B-D, B-E, C-F, D-E, E-F</p>
<p><strong>Question:</strong> If you perform DFS starting from vertex A and always visit neighbors in alphabetical order, draw the resulting DFS tree. Which edges from the original graph are NOT in the DFS tree?</p>
</div>
<aside class="notes">
<p><strong>Answer:</strong></p>
<p><strong>DFS Traversal Process (visiting neighbors alphabetically):</strong> 1. Start at A (mark visited) 2. Visit A’s neighbor B (mark visited) 3. Visit B’s neighbor D (C is A’s neighbor but we explore B fully first) 4. Visit D’s neighbor E (mark visited) 5. Visit E’s neighbor F (mark visited) 6. Backtrack to E, then D, then B, then A 7. Visit A’s neighbor C (mark visited) 8. No unvisited neighbors from C</p>
<p><strong>DFS Tree edges:</strong> - A-B (A to B) - B-D (B to D)<br>
- D-E (D to E) - E-F (E to F) - A-C (A to C)</p>
<p><strong>Tree structure:</strong></p>
<pre><code>      A
     / \
    B   C
    |
    D
    |
    E
    |
    F</code></pre>
<p><strong>Edges NOT in the DFS tree (non-tree edges/back edges):</strong> - B-E (E was already visited via D when we explored from B) - C-F (F was already visited when we got to C) - D-E is in the tree, so the non-tree edges are: <strong>B-E and C-F</strong></p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- 
## Next Week Reading:
- FDS - Lambert 
    - Chapter 12
- DS&A - John et al.
    - Chapter 14 -->

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="ch13.1_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="ch13.1_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="ch13.1_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="ch13.1_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="ch13.1_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="ch13.1_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="ch13.1_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="ch13.1_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="ch13.1_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="ch13.1_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="ch13.1_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>